version: '2'
services:
  microservice-discovery-eureka:
    image: itmuch/microservice-discovery-eureka:0.0.1-SNAPSHOT
    hostname: discovery
    ports:
      - 8761:8761
  microservice-provider-user:
    image: itmuch/microservice-provider-user:0.0.1-SNAPSHOT
    links: 
      - microservice-discovery-eureka
  microservice-consumer-movie-ribbon-hystrix:
    image: itmuch/microservice-consumer-movie-ribbon-hystrix:0.0.1-SNAPSHOT
    links: 
      - microservice-discovery-eureka
  microservice-gateway:
    image: itmuch/microservice-gateway-zuul:0.0.1-SNAPSHOT
    links: 
      - microservice-discovery-eureka
  microservice-hystrix-dashboard:
    image: itmuch/microservice-hystrix-dashboard:0.0.1-SNAPSHOT
    links: 
      - microservice-discovery-eureka
  microservice-hystrix-turbine:
    image: itmuch/microservice-hystrix-turbine:0.0.1-SNAPSHOT
    links: 
      - microservice-discovery-eureka
