server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: microservice-provider-user
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
  kafka:
    bootstrap-servers: localhost:9092


# 注：Spring Boot2不能用spring.datasource.schema/data指定初始化SQL脚本，否则与actuator不能共存
# 原因：https://github.com/spring-projects/spring-boot/issues/13042
# https://github.com/spring-projects/spring-boot/issues/13539