version: '2'
services:
  microservice-discovery-eureka-ha1:
    image: itmuch/microservice-discovery-eureka:0.0.1-SNAPSHOT
    hostname: peer1
    ports:
    - 8761:8761
  microservice-discovery-eureka-ha2:
    image: itmuch/microservice-discovery-eureka:0.0.1-SNAPSHOT
    hostname: peer2
    ports:
    - 8762:8762
  microservice-provider-user:
    image: itmuch/microservice-provider-user:0.0.1-SNAPSHOT
  microservice-consumer-movie-ribbon-hystrix:
    image: itmuch/microservice-consumer-movie-ribbon-hystrix:0.0.1-SNAPSHOT
  microservice-hystrix-dashboard:
    image: itmuch/microservice-hystrix-dashboard:0.0.1-SNAPSHOT
  microservice-hystrix-turbine:
    image: itmuch/microservice-hystrix-turbine:0.0.1-SNAPSHOT
  microservice-gateway:
    image: itmuch/microservice-gateway-zuul:0.0.1-SNAPSHOT