version: "2"
services:
  ambassador:
    image: svendowideit/ambassador
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "-name peer1 -name peer2"
  microservice-discovery-eureka-ha1:
    hostname: peer1
    image: itmuch/microservice-discovery-eureka-ha:0.0.1-SNAPSHOT
    links: 
      - "ambassador:peer2"
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=peer1
  microservice-discovery-eureka-ha2:
    hostname: peer2
    image: itmuch/microservice-discovery-eureka-ha:0.0.1-SNAPSHOT
    links:
    - "ambassador:peer1"
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=peer2
networks:
  eureka-net:
    driver: overlay