server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  security:
    user:
      name: user                # 配置登录的账号是user
      password: password123     # 配置登录的密码是password123
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
